// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package deploy

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"
)

// goldenCase is one fingerprint produced by the web client's own code.
type goldenCase struct {
	Files []struct {
		Path   string `json:"path"`
		Base64 string `json:"base64"`
	} `json:"files"`
	Hash string `json:"hash"`
}

// TestContentHashMatchesWebClientGolden pins the fingerprint against values
// generated by running the web client's local-html-share module itself, not by
// re-deriving the algorithm in Go. Anything the two implementations could
// disagree on -- UTF-16 versus UTF-8 path order, HTML escaping inside
// JSON.stringify, which extensions hash by content, how an extension is read
// off a path -- shows up here as a mismatched digest rather than as a GUI that
// silently reports "out of sync" forever.
//
// The values come from executing the web client's own local-html-share module
// under Node (type stripping is enough -- the module is erasable TypeScript),
// feeding it the same file sets. Regenerating therefore needs that module; do
// not hand-edit the digests, and do not regenerate them from this Go code,
// which would turn the test into a tautology.
func TestContentHashMatchesWebClientGolden(t *testing.T) {
	raw, err := os.ReadFile("testdata/contenthash_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var cases map[string]goldenCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("golden file has no cases")
	}

	for name, c := range cases {
		t.Run(name, func(t *testing.T) {
			files := make([]HashFile, 0, len(c.Files))
			for _, f := range c.Files {
				b, err := base64.StdEncoding.DecodeString(f.Base64)
				if err != nil {
					t.Fatalf("decode %q: %v", f.Path, err)
				}
				files = append(files, HashFile{Path: f.Path, Raw: b})
			}
			got, err := ContentHash(files)
			if err != nil {
				t.Fatalf("ContentHash: %v", err)
			}
			if got != c.Hash {
				t.Errorf("digest differs from the web client\n got %s\nwant %s", got, c.Hash)
			}
		})
	}
}
